### PR TITLE
added Tekkie Consulting and Georgiana Gligor personal website

### PR DESCRIPTION
**Pull request by georgiana-gligor**

### CODE REVIEW

**Comment by georgiana-gligor** [comment]
Hi @dragonmantank I know you're the new maintainer of Sculpin.
I've been diligently adding a "powered by Sculpin" footer to the static websites I maintain, 2 of which are in this PR.
The 3rd one I'll open a PR for is httsp://romaniaphp.ro/
Could we expect such PRs to be merged?

**Comment by beryllium** [comment]
This looks fine to go in, I'm not sure what the delay has been - I'll check with @dragonmantank about it.

**Comment by dragonmantank** [comment]
Merged.

It was a combination of "need to manually merge these since a bunch are hanging" and slipping of my mind. This has been merged and pushed. Thanks!

**Comment by georgiana-gligor** [comment]
thank you!

**Pull request merged**
