### PR TITLE
Added my own blog since it just moved over

### PR DESCRIPTION
**Pull request by WyriHaximus**

### CODE REVIEW

**Comment by davedevelopment** [comment]
Cool!

**Comment by WyriHaximus** [comment]
Honestly I could just have commited it but this feels better way to go ;).

**Comment by davedevelopment** [comment]
@WyriHaximus I'll send a PR to add my blog and you can merge it :)

**Comment by WyriHaximus** [comment]
@davedevelopment :+1:

**Comment by simensen** [comment]
awesomesauce, published!

**Pull request merged**
