### PR TITLE
Adding a new section for listing Sculpin extensions

### PR DESCRIPTION
**Pull request by beryllium**

### CODE REVIEW

**Comment by davedevelopment** [comment]
:+1:

**Comment by WyriHaximus** [comment]
:+1:

**Comment by dragonmantank** [comment]
+1

Though we should add Fillet there too :P https://github.com/dragonmantank/fillet-sculpin-bundle

**Comment by WyriHaximus** [comment]
@dragonmantank you can always make a PR to @beryllium PR :+1:

**Comment by simensen** [comment]
@beryllium How would you feel about pulling this out into an _extensions content type? We don't have to link to the actual extension pages but it might be nice to start handling these types of things with custom content types so that people aren't all editing the same chunk of code like they do w/ the community sites.

If you don't think you'd have time to do that in the next few days we can merge this and see if someone else has the time to migrate it.

**Comment by beryllium** [comment]
Replaced by #122

**Pull request closed without merging**
