### PR TITLE
Add mascot to navbar and use spaces in CSS file

### PR DESCRIPTION
**Pull request by ibrasho**

### CODE REVIEW

**Comment by WouterJ** [comment]
Why tab?

**Comment by simensen** [comment]
Yeah, not a fan of that. I know that sometimes my editors aren't configured to do spaces instead of tabs for css so it is possible there were tabs somewhere in here already? If so, my bad. :-/

**Comment by ibrasho** [comment]
I'm not a fan of tabs too. I found more tabs than spaces in the CSS file so I thought that was the preference.

Updated.

**Comment by simensen** [comment]
Thanks!

**Pull request merged**
